# Generated by Django 4.2.10 on 2025-06-27 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('text', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('speed', models.FloatField(default=1.0)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tts_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
